#pragma once
#ifndef __RESOURCE_H_
#define __RESOURCE_H_
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Resources.rc
//
#define IDD_DIALOG1                     12101
#define IDD_PAYLOADS                    102
#define IDD_VIEWTXT                     103
#define IDD_FAIRING                     104
#define IDD_PARTICLE                    105
#define IDD_MISC                        106
#define IDD_TEX                         107
#define IDD_BOOSTERS                    108
#define IDD_BOOSTER_CURVE               109
#define IDD_STAGES                      110
#define IDD_STAGE_ULLAGE                111
#define IDD_INTERSTAGES                 112
#define IDD_LES                         113
#define IDD_ADAPTER                     114
#define IDD_FX                          115
#define IDD_SCENARIO                    116
#define IDC_TREE1                       1001
#define IDC_PLD_RENDER                  1004
#define IDC_PLD_LIVE                    1005
#define IDC_PLD_MESHNAME                1007
#define IDC_PLD_HEIGHT                  1008
#define IDC_PLD_DIAM                    1009
#define IDC_PLD_MASS                    1010
#define IDC_PLD_MODULE                  1011
#define IDC_PLD_NAME                    1012
#define IDC_PLD_OFFX                    1013
#define IDC_PLD_OFFY                    1014
#define IDC_PLD_OFFZ                    1015
#define IDC_PLD_SPDX                    1016
#define IDC_PLD_SPDY                    1017
#define IDC_PLD_SPDZ                    1018
#define IDC_PLD_RSPDX                   1019
#define IDC_PLD_RSPDY                   1020
#define IDC_PLD_RSPDZ                   1021
#define IDC_PLD_ROTX                    1022
#define IDC_BOOSTER_N                   1022
#define IDC_PLD_ROTY                    1023
#define IDC_BOOSTER_ANGLE               1023
#define IDC_PLD_ROTZ                    1024
#define IDC_PLD_UPDMSH                  1025
#define IDC_PLD_ID                      1026
#define IDC_PLD_STOREVALS               1027
#define IDC_PLD_MULTIMSHNAME            1028
#define IDC_PLD_PICK                    1029
#define IDC_PLD_PICKMODULE              1030
#define IDC_PLD_MULTIMSH                1032
#define IDC_PLD_MULTIOFF                1033
#define IDC_VIEWLOG                     1034
#define IDC_VIEWFILE                    1035
#define IDC_PLD_ADDPLD                  1036
#define IDC_VIEWINI                     1037
#define IDC_PLD_DELPLD                  1037
#define IDC_SAVEINI                     1038
#define IDC_FAIR_HIDE                   1038
#define IDC_RESET                       1039
#define IDC_FAIR_MESHNAME               1039
#define IDC_FAIR_OFFX                   1040
#define IDC_FAIR_OFFY                   1041
#define IDC_FAIR_OFFZ                   1042
#define IDC_FAIR_N                      1043
#define IDC_FAIR_ANGLE                  1044
#define IDC_FAIR_HEIGHT                 1045
#define IDC_FAIR_DIAM                   1046
#define IDC_FAIR_EMPTYMASS              1047
#define IDC_FAIR_MODULE                 1048
#define IDC_PART_V0                     1048
#define IDC_FAIR_HIDEHALF               1049
#define IDC_PART_SRCSPREAD              1049
#define IDC_FAIR_SPDX                   1050
#define IDC_PART_LIFETIME               1050
#define IDC_FAIR_SPDY                   1051
#define IDC_PART_GROWTHRATE             1051
#define IDC_FAIR_SPDZ                   1052
#define IDC_PART_ATMSLOWDOWN            1052
#define IDC_FAIR_RSPDX                  1053
#define IDC_PART_LMIN                   1053
#define IDC_FAIR_RSPDY                  1054
#define IDC_PART_LMAX                   1054
#define IDC_FAIR_RSPDZ                  1055
#define IDC_PART_AMIN                   1055
#define IDC_FAIR_PICKMODULE             1056
#define IDC_PART_AMAX                   1056
#define IDC_FAIR_PICKMESH               1057
#define IDC_PART_TEX                    1057
#define IDC_FAIR_STOREVALS              1058
#define IDC_PART_GFS                    1058
#define IDC_FAIR_DELFAIR                1059
#define IDC_PART_GFR                    1059
#define IDC_FAIR_ADDFAIR                1060
#define IDC_PART_STOREVALS              1061
#define IDC_PART_DELPART                1062
#define IDC_PART_ADDPART                1063
#define IDC_PART_ID                     1064
#define IDC_PART_NAME                   1065
#define IDC_PART_SRCSIZE                1066
#define IDC_PART_SRCRATE                1067
#define IDC_PART_ENABLEGROWING          1068
#define IDC_PART_TESTPART               1069
#define IDC_PART_LEVELMAP               1071
#define IDC_PART_ATMSMAP                1072
#define IDC_PART_LTYPE                  1073
#define IDC_PART_SLIDERLEVEL            1074
#define IDC_FILENAME                    1075
#define IDC_MISC_COG                    1076
#define IDC_MISC_VERTICALANGLE          1077
#define IDC_MISC_PADMODULE              1078
#define IDC_MISC_GNCDEBUG               1079
#define IDC_MISC_TELEMETRY              1080
#define IDC_MISC_THRUSTREALPOS          1081
#define IDC_MISC_WPADMODULE             1082
#define IDC_MISC_FOCUS                  1083
#define IDC_MISC_STOREVALS              1084
#define IDC_TEX_STOREVALS               1085
#define IDC_TEX_TEX1                    1086
#define IDC_TEX_TEX2                    1087
#define IDC_BOOSTER_ID                  1087
#define IDC_TEX_TEX3                    1088
#define IDC_BOOSTER_STOREVALS           1088
#define IDC_TEX_TEX4                    1089
#define IDC_BOOSTER_MESHNAME            1089
#define IDC_TEX_TEX5                    1090
#define IDC_BOOSTER_OFFX                1090
#define IDC_TEX_TEX6                    1091
#define IDC_BOOSTER_OFFY                1091
#define IDC_TEX_TEX7                    1092
#define IDC_BOOSTER_OFFZ                1092
#define IDC_TEX_TEX8                    1093
#define IDC_BOOSTER_PICK                1093
#define IDC_TEX_TEX9                    1094
#define IDC_BOOSTER_HEIGHT              1094
#define IDC_TEX_TEX10                   1095
#define IDC_BOOSTER_DIAM                1095
#define IDC_TEX_TEX11                   1096
#define IDC_BOOSTER_THRUST              1096
#define IDC_TEX_TEX12                   1097
#define IDC_BOOSTER_EMPTYMASS           1097
#define IDC_TEX_TEX13                   1098
#define IDC_BOOSTER_FUELMASS            1098
#define IDC_TEX_TEX14                   1099
#define IDC_BOOSTER_BURNTIME            1099
#define IDC_TEX_TEX15                   1100
#define IDC_BOOSTER_BURNDELAY           1100
#define IDC_TEX_TEX16                   1101
#define IDC_BOOSTER_MODULE              1101
#define IDC_BOOSTER_SPDX                1102
#define IDC_BOOSTER_SPDY                1103
#define IDC_BOOSTER_SPDZ                1104
#define IDC_BOOSTER_RSPDX               1105
#define IDC_BOOSTER_RSPDY               1106
#define IDC_BOOSTER_RSPDZ               1107
#define IDC_BOOSTER_RESISP              1108
#define IDC_BOOSTER_DELBOOSTER          1109
#define IDC_BOOSTER_ADDBOOSTER          1110
#define IDC_BOOSTER_ENGDIAM             1111
#define IDC_BOOSTER_ENGTEX              1112
#define IDC_BOOSTER_ENGPS1              1113
#define IDC_BOOSTER_ENGPS2              1114
#define IDC_BOOSTER_SHOWCURVE           1115
#define IDC_BOOSTER_ENGN                1116
#define IDC_BOOSTER_EXPBX               1117
#define IDC_BOOSTER_ENGDIRX             1118
#define IDC_BOOSTER_CURVEGRAPH          1118
#define IDC_BOOSTER_ENGDIRY             1119
#define IDC_BOOSTER_ENGDIRZ             1120
#define IDC_CURVEX1                     1120
#define IDC_CURVEY1                     1121
#define IDC_BOOSTER_EXPBY               1121
#define IDC_BOOSTER_ENG1X               1122
#define IDC_CURVEX2                     1122
#define IDC_BOOSTER_ENG1Y               1123
#define IDC_CURVEY2                     1123
#define IDC_BOOSTER_ENG1Z               1124
#define IDC_CURVEX3                     1124
#define IDC_BOOSTER_ENG2X               1125
#define IDC_CURVEY3                     1125
#define IDC_BOOSTER_ENG2Y               1126
#define IDC_CURVEX4                     1126
#define IDC_BOOSTER_ENG2Z               1127
#define IDC_CURVEY4                     1127
#define IDC_BOOSTER_ENG3X               1128
#define IDC_CURVEX5                     1128
#define IDC_BOOSTER_ENG3Y               1129
#define IDC_CURVEY5                     1129
#define IDC_BOOSTER_ENG3Z               1130
#define IDC_CURVEX6                     1130
#define IDC_CURVEY6                     1131
#define IDC_BOOSTER_EXPBZ               1131
#define IDC_CURVEX7                     1132
#define IDC_BOOSTER_EXPBPS              1132
#define IDC_CURVEY7                     1133
#define IDC_BOOSTER_EXPBANT             1133
#define IDC_BOOSTER_ENG4X               1134
#define IDC_CURVEX8                     1134
#define IDC_BOOSTER_ENG4Y               1135
#define IDC_CURVEY8                     1135
#define IDC_BOOSTER_ENG4Z               1136
#define IDC_CURVEX9                     1136
#define IDC_CURVEY9                     1137
#define IDC_STAGE_BATTERY               1137
#define IDC_CURVEX10                    1138
#define IDC_STAGE_PARTPACKTOENG         1138
#define IDC_STAGE_ULLAGEDIRY            1138
#define IDC_CURVEY10                    1139
#define IDC_STAGE_PITCHTHRUST           1139
#define IDC_CURVE_N                     1140
#define IDC_STAGE_ROLLTHRUST            1140
#define IDC_STAGE_ULLAGEPOSY            1140
#define IDC_CURVE_SAVE                  1141
#define IDC_STAGE_YAWTHRUST             1141
#define IDC_CURVE_CLOSE                 1142
#define IDC_BOOSTER_PICKMODULE          1142
#define IDC_BOOSTER_WEXPB               1143
#define IDC_STAGE_ULLAGEDIRZ            1143
#define IDC_CURVE_UPDATE                1144
#define IDC_STAGE_REIGNITABLE           1144
#define IDC_STAGE_ULLAGEPOSZ            1144
#define IDC_STAGE_ENG5X                 1145
#define IDC_STAGE_ENG5Y                 1146
#define IDC_STAGE_ENG5Z                 1147
#define IDC_STAGE_ENG1SCALE             1148
#define IDC_STAGE_ENG2SCALE             1149
#define IDC_STAGE_ENG3SCALE             1150
#define IDC_STAGE_ENG4SCALE             1151
#define IDC_STAGE_ENG5SCALE             1152
#define IDC_STAGE_PARTPACKCHECK         1153
#define IDC_STAGE_PTDEF                 1154
#define IDC_STAGE_RTDEF                 1155
#define IDC_STAGE_YTDEF                 1156
#define IDC_STAGE_LINEARTHRUST          1157
#define IDC_STAGE_LTDEF                 1158
#define IDC_STAGE_SHOWULLAGE            1159
#define IDC_STAGE_MESHNAME              1160
#define IDC_STAGE_PICK                  1161
#define IDC_STAGE_OFFX                  1162
#define IDC_STAGE_OFFY                  1163
#define IDC_STAGE_OFFZ                  1164
#define IDC_STAGE_ID                    1165
#define IDC_STAGE_HEIGHT                1166
#define IDC_STAGE_DIAM                  1167
#define IDC_STAGE_THRUST                1168
#define IDC_STAGE_EMPTYMASS             1169
#define IDC_STAGE_FUELMASS              1170
#define IDC_STAGE_BURNTIME              1171
#define IDC_STAGE_IGNITEDELAY           1172
#define IDC_STAGE_RESISP                1173
#define IDC_STAGE_DELSTAGE              1174
#define IDC_STAGE_ADDSTAGE              1175
#define IDC_STAGE_STOREVALS             1176
#define IDC_STAGE_ENGDIAM               1177
#define IDC_STAGE_ENGTEX                1178
#define IDC_STAGE_ENGPS1                1179
#define IDC_STAGE_ENGPS2                1180
#define IDC_STAGE_ENGDIRX               1181
#define IDC_STAGE_ENGDIRY               1182
#define IDC_STAGE_ENGDIRZ               1183
#define IDC_STAGE_ENGN                  1184
#define IDC_STAGE_SHOWINTERSTAGE        1185
#define IDC_STAGE_ENG2X                 1186
#define IDC_STAGE_ENG2Y                 1187
#define IDC_STAGE_ENG2Z                 1188
#define IDC_STAGE_ENG3X                 1189
#define IDC_STAGE_ENG3Y                 1190
#define IDC_STAGE_ENG3Z                 1191
#define IDC_STAGE_ENG4X                 1192
#define IDC_STAGE_ENG4Y                 1193
#define IDC_STAGE_ENG4Z                 1194
#define IDC_STAGE_MODULE                1195
#define IDC_STAGE_PICKMODULE            1196
#define IDC_STAGE_SPDX                  1197
#define IDC_STAGE_SPDY                  1198
#define IDC_STAGE_SPDZ                  1199
#define IDC_STAGE_RSPDX                 1200
#define IDC_STAGE_RSPDY                 1201
#define IDC_STAGE_RSPDZ                 1202
#define IDC_STAGE_WEXPB                 1203
#define IDC_STAGE_EXPBX                 1204
#define IDC_STAGE_EXPBY                 1205
#define IDC_STAGE_EXPBZ                 1206
#define IDC_STAGE_EXPBPS                1207
#define IDC_STAGE_EXPBANT               1208
#define IDC_STAGE_ENG1X                 1209
#define IDC_STAGE_ENG1Y                 1210
#define IDC_STAGE_ENG1Z                 1211
#define IDC_STAGE_BATTERYCHECK          1212
#define IDC_STAGE_ULLAGEC               1213
#define IDC_STAGE_ULLAGETHRUST          1214
#define IDC_STAGE_ULLAGEANT             1215
#define IDC_STAGE_ULLAGEOVERLAP         1216
#define IDC_STAGE_ULLAGEN               1217
#define IDC_STAGE_ULLAGEANGLE           1218
#define IDC_STAGE_ULLAGEDIAM            1219
#define IDC_STAGE_ULLAGELENGTH          1220
#define IDC_STAGE_ULLAGEDIRX            1221
#define IDC_STAGE_ULLAGEPOSX            1222
#define IDC_STAGE_ULLAGERECTFACTOR      1223
#define IDC_STAGE_ULLAGESAVE            1224
#define IDC_STAGE_ULLAGECLOSE           1225
#define IDC_ADDGENERAL                  1226
#define IDC_INTERSTAGE_MESHNAME         1227
#define IDC_SAVEGENERAL                 1227
#define IDC_INTERSTAGE_PICK             1228
#define IDC_INTERSTAGE_PICKMESH         1228
#define IDC_INTERSTAGE_OFFX             1229
#define IDC_INTERSTAGE_OFFY             1230
#define IDC_INTERSTAGE_OFFZ             1231
#define IDC_INTERSTAGE_HEIGHT           1232
#define IDC_INTERSTAGE_DIAM             1233
#define IDC_INTERSTAGE_EMPTYMASS        1234
#define IDC_INTERSTAGE_SEPARATIONDELAY  1235
#define IDC_INTERSTAGE_MODULE           1236
#define IDC_INTERSTAGE_PICKMODULE       1237
#define IDC_INTERSTAGE_SPDX             1238
#define IDC_INTERSTAGE_SPDY             1239
#define IDC_INTERSTAGE_SPDZ             1240
#define IDC_INTERSTAGE_RSPDX            1241
#define IDC_INTERSTAGE_RSPDY            1242
#define IDC_INTERSTAGE_RSPDZ            1243
#define IDC_INTERSTAGE_SAVE             1244
#define IDC_INTERSTAGE_CLOSE            1245
#define IDC_INTERSTAGE_WINTER           1246
#define IDC_LES_WLES                    1247
#define IDC_LES_MESHNAME                1248
#define IDC_LES_PICKMESH                1249
#define IDC_FXMACH_PSTREAM              1249
#define IDC_LES_OFFX                    1250
#define IDC_LES_OFFY                    1251
#define IDC_LES_OFFZ                    1252
#define IDC_LES_HEIGHT                  1253
#define IDC_FXVENT_OFF2X                1253
#define IDC_LES_DIAM                    1254
#define IDC_FXVENT_OFF2Y                1254
#define IDC_LES_EMPTYMASS               1255
#define IDC_FXVENT_OFF2Z                1255
#define IDC_LES_MODULE                  1256
#define IDC_FXVENT_OFF3X                1256
#define IDC_LES_PICKMODULE              1257
#define IDC_FXVENT_OFF3Y                1257
#define IDC_LES_SPDX                    1258
#define IDC_FXVENT_OFF3Z                1258
#define IDC_LES_SPDY                    1259
#define IDC_FXVENT_OFF4X                1259
#define IDC_LES_SPDZ                    1260
#define IDC_FXVENT_OFF4Y                1260
#define IDC_LES_RSPDX                   1261
#define IDC_FXVENT_OFF4Z                1261
#define IDC_LES_RSPDY                   1262
#define IDC_FXVENT_OFF5X                1262
#define IDC_LES_RSPDZ                   1263
#define IDC_FXVENT_OFF5Y                1263
#define IDC_LES_STOREVALS               1264
#define IDC_FXVENT_OFF5Z                1265
#define IDC_FXVENT_OFF6X                1266
#define IDC_FAIR_WFAIR                  1267
#define IDC_FXVENT_OFF6Y                1267
#define IDC_ADAPTER_STOREVALS           1268
#define IDC_FXVENT_OFF6Z                1268
#define IDC_ADAPTER_MESHNAME            1269
#define IDC_FXVENT_OFF7X                1269
#define IDC_ADAPTER_OFFX                1270
#define IDC_FXVENT_OFF7Y                1270
#define IDC_ADAPTER_OFFY                1271
#define IDC_FXVENT_OFF7Z                1271
#define IDC_ADAPTER_OFFZ                1272
#define IDC_FXVENT_OFF8X                1272
#define IDC_ADAPTER_HEIGHT              1273
#define IDC_FXVENT_OFF8Y                1273
#define IDC_ADAPTER_DIAM                1274
#define IDC_FXVENT_OFF8Z                1274
#define IDC_ADAPTER_EMPTYMASS           1275
#define IDC_FXVENT_OFF9X                1275
#define IDC_FXVENT_OFF9Y                1276
#define IDC_ADAPTER_WADAPTER            1277
#define IDC_FXVENT_OFF9Z                1277
#define IDC_ADAPTER_PICKMESH            1278
#define IDC_FXVENT_OFF10X               1278
#define IDC_FXVENT_OFF10Y               1279
#define IDC_FXVENT_OFF10Z               1280
#define IDC_FXVENT_CB                   1281
#define IDC_FXVENT_TF1                  1282
#define IDC_FXVENT_TF2                  1283
#define IDC_FXVENT_TF3                  1284
#define IDC_FXVENT_TF4                  1285
#define IDC_FXVENT_TF5                  1286
#define IDC_FXVENT_TF6                  1287
#define IDC_FXVENT_TF7                  1288
#define IDC_FXVENT_TF8                  1289
#define IDC_FXVENT_TF9                  1290
#define IDC_FXVENT_TF10                 1291
#define IDC_FXVENT_DIR1X                1292
#define IDC_FXVENT_DIR1Y                1293
#define IDC_FXVENT_DIR1Z                1294
#define IDC_FXVENT_DIR2X                1295
#define IDC_FXVENT_DIR2Y                1296
#define IDC_FXVENT_DIR2Z                1297
#define IDC_FXVENT_DIR3X                1298
#define IDC_FXVENT_DIR3Y                1299
#define IDC_FXVENT_DIR3Z                1300
#define IDC_FXVENT_DIR4X                1301
#define IDC_FXVENT_DIR4Y                1302
#define IDC_FXVENT_DIR4Z                1303
#define IDC_FXVENT_DIR5X                1304
#define IDC_FXVENT_DIR5Y                1305
#define IDC_FXVENT_DIR5Z                1306
#define IDC_FXVENT_DIR6X                1307
#define IDC_FXVENT_DIR6Y                1308
#define IDC_FXVENT_DIR6Z                1309
#define IDC_FXVENT_DIR7X                1310
#define IDC_FXVENT_DIR7Y                1311
#define IDC_FXVENT_DIR7Z                1312
#define IDC_FXVENT_DIR8X                1313
#define IDC_FXVENT_DIR8Y                1314
#define IDC_FXVENT_DIR8Z                1315
#define IDC_FXVENT_DIR9X                1316
#define IDC_FXVENT_DIR9Y                1317
#define IDC_FXVENT_DIR9Z                1318
#define IDC_FXVENT_DIR10X               1319
#define IDC_FXVENT_DIR10Y               1320
#define IDC_FXVENT_DIR10Z               1321
#define IDC_FXMACH_OFF1X                1322
#define IDC_FXMACH_OFF1Y                1323
#define IDC_FXMACH_OFF1Z                1324
#define IDC_FXMACH_OFF2X                1325
#define IDC_FXMACH_OFF2Y                1326
#define IDC_FXMACH_OFF2Z                1327
#define IDC_FXMACH_OFF3X                1328
#define IDC_FXMACH_OFF3Y                1329
#define IDC_FXMACH_OFF3Z                1330
#define IDC_FXMACH_OFF4X                1331
#define IDC_FXMACH_OFF4Y                1332
#define IDC_FXMACH_OFF4Z                1333
#define IDC_FXMACH_OFF5X                1334
#define IDC_FXMACH_OFF5Y                1335
#define IDC_FXMACH_OFF5Z                1336
#define IDC_FXMACH_OFF6X                1337
#define IDC_FXMACH_OFF6Y                1338
#define IDC_FXMACH_OFF6Z                1339
#define IDC_FXMACH_OFF7X                1340
#define IDC_FXMACH_OFF7Y                1341
#define IDC_FXMACH_OFF7Z                1342
#define IDC_FXMACH_OFF8X                1343
#define IDC_FXMACH_OFF8Y                1344
#define IDC_FXMACH_OFF8Z                1345
#define IDC_FXMACH_OFF9X                1346
#define IDC_FXMACH_OFF9Y                1347
#define IDC_FXMACH_OFF9Z                1348
#define IDC_FXMACH_OFF10X               1349
#define IDC_FXMACH_OFF10Y               1350
#define IDC_LES_OFFZ40                  1351
#define IDC_FXMACH_OFF10Z               1351
#define IDC_FXMACH_MIN                  1352
#define IDC_FXMACH_MAX                  1353
#define IDC_FXMACH_DIRX                 1354
#define IDC_FXMACH_DIRY                 1355
#define IDC_FXMACH_DIRZ                 1356
#define IDC_FXVENT_WVENT                1357
#define IDC_FXVENT_PSTREAM              1358
#define IDC_FXVENT_OFF1X                1359
#define IDC_FXMACH_CB                   1360
#define IDC_FXVENT_OFF1Y                1361
#define IDC_FXVENT_OFF1Z                1364
#define IDC_FXMACH_WMACH                1365
#define IDC_FX_STOREVALS                1366
#define IDC_FXLAUNCH_WLAUNCH            1367
#define IDC_FXLAUNCH_N                  1368
#define IDC_FXLAUNCH_HEIGHT             1369
#define IDC_FXLAUNCH_DISTANCE           1370
#define IDC_SCN_SHIPNAME                1370
#define IDC_FXLAUNCH_ANGLE              1371
#define IDC_SCN_DATE                    1371
#define IDC_FXLAUNCH_CUTOFF             1372
#define IDC_SCN_NOW                     1372
#define IDC_FXLAUNCH_PS1                1373
#define IDC_SCN_LAT                     1373
#define IDC_FXLAUNCH_PS2                1374
#define IDC_SCN_LNG                     1374
#define IDC_SCN_HEADING                 1375
#define IDC_SCN_CONFIGFILE              1376
#define IDC_SCN_GNCFILE                 1377
#define IDC_SCN_TLMFILE                 1378
#define IDC_SCN_WGNCFILE                1379
#define IDC_SCN_WTLMFILE                1380
#define IDC_SCN_COMPLEX                 1381
#define IDC_SCN_GROWINGPART             1382
#define IDC_SCN_FAILURES                1383
#define IDC_SCN_PROBABILITY             1384
#define IDC_SCN_CAMERA                  1385
#define IDC_SCN_HANGAR                  1386
#define IDC_SCN_CRAWLER                 1387
#define IDC_SCN_PEGDEFAULT              1388
#define IDC_SCN_ALTSTEPS0               1389
#define IDC_SCN_ALTSTEPS1               1390
#define IDC_SCN_ALTSTEPS2               1391
#define IDC_SCN_ALTSTEPS3               1392
#define IDC_SCN_PEGPITCHLIMIT           1393
#define IDC_SCN_PEGMCINTERVAL           1394
#define IDC_SCN_SAVESCN                 1395
#define IDC_SCN_SAVELOADSCN             1396
#define IDC_SCN_GETCURRPOS              1397
#define IDC_SCN_FILENAME                1398
#define IDC_SCN_NOW2                    1399
#define IDC_SCN_FNDEFAULT               1399
#define IDC_TAB1                        1400
#define IDC_EDIT1                       1401

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1398
#define _APS_NEXT_SYMED_VALUE           11101
#endif
#endif

#endif //!__RESOURCE_H_

